### ISSUE TITLE
ModelScope, VideoCraft2 videos

### ISSUE THREAD

**Issue by jnumgi** [WangWenhao0716/VidProM#1]
Hi, thank you for curating this collection! I don't see video outputs from modelscope and videocraft at HuggingFace (https://huggingface.co/datasets/WenhaoWang/VidProM/tree/main). I wanted to check-in if I am missing something or it hasn't been uploaded yet?

**Comment by WangWenhao0716** [comment]
Hi, thanks for pointing this out. We plan to upload videos from modelscope and videocraft  at the beginning of April. 

Thanks for understanding this is a very tremendous and expensive workload.

**Comment by WangWenhao0716** [comment]
released.
